---
- file:
    state: directory
    mode: "2751"
    path: "{{item}}"
  with_items:
  - "{{cops_generic_dir}}"
  - "{{cops_generic_dir}}/local/postgresql/data"
  - "{{cops_generic_dir}}/local/backup"
  - "{{cops_generic_dir}}/local/backup/data"
  - "{{cops_generic_dir}}/local/backup/setup"
- name: Synchronise files inside the environment (deleguation)
  delegate_to: "localhost"
  synchronize:
    compress: false
    ssh_args: "{{cops_generic_sshargs}}"
    src: "../../../../../"
    dest: "{{cops_generic_dir}}/"
    rsync_opts: ["-azv", "--exclude", ".ansible", "--exclude", "local"]
    #update_opts: '--recursive'
- template:
    src: "template.env"
    dest: "{{cops_generic_dir}}/template.env"
    mode: "0640"
    trim_blocks: false
