---
# APP
- hosts: "{{generic_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_generic_lifecycle_app|default(true)"]
    tags: ["cops_generic_lifecycle_app"]
    include_role: {name: generic_vars, allow_duplicates: false}
  - when: ["cops_generic_lifecycle_app"]
    tags: ["cops_generic_lifecycle_app"]
    block:
    - include_role: {name: generic,    allow_duplicates: false}
